name: clean_e_commerce_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1 # Moved here
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
